var rnsCategoryMapping={
ACQ: "Acquisition",
ACS: "Annual Financial Report",
AGM: "AGM Statement",
AGR: "Re Agreement",
AIM: "AIM Admission - Update",
AIU: "Annual Information Update",
AMO: "AIM Notice (number inserted)",
APM: "Second Price Monitoring Extn",
APP: "Change of Adviser",
ARI: "Announcement re: Rights Issue",
BLR: "Blocklisting Interim Review",
BOA: "Directorate Change",
BRC: "Base Rate Change",
CAN: "Change of Name",
CAR: "Capital Reorganisation",
CAS: "Compulsory Acqn of Shares",
CIR: "Circ re. (add further text)",
CMC: "Compliance with Model Code",
CNR: "Change to the Nomad Register",
CNT: "Re Contract",
CON: "Conversion of Securities",
COS: "Company Secretary Change",
CRO: "Change of Registered Office",
DCC: "Rule 8.1- (add security name)",
DIS: "Disposal",
DIV: "Dividend Declaration",
DOC: "Doc re. (add further text)",
DRL: "Drilling Report",
DSP: "Disclosure of Short Position",
EDB: "Edgar Batch Announcement",
EFN: "City Events Wire Update",
EGM: "EGM Statement",
EMM: "EPT Disclosure",
EOD: "Final Announcement Released",
EXC: "Exch Suspension/Restoration",
FEO: "FORM 8.5 (EPT/NON-RI)",
FON: "Formal Notice",
FR: "Final Results",
FTS: "FTSE Only (Add Headline)",
FUR: "Further re (add further text)",
GEO: "Geographical Distribution",
HOL: "Holding(s) in Company",
IMS: "Interim Management Statement",
IOD: "Issue of Debt",
IOE: "Issue of Equity",
IR: "Half Yearly Report",
ISE: "ISE Only - (Add headline)",
JVE: "Re Joint Venture",
LIS: "Additional Listing",
LOI: "Letter of Intent Signed",
MER: "Merger Update",
MMH: "Market Maker Holding",
MSC: "Miscellaneous",
NAR: "New Accounting Ref Date",
NAV: "Net Asset Value(s)",
NOA: "Notice of AGM",
NOE: "Notice of EGM",
NOR: "Notice of Results",
NOT: "Official List Notice",
NOV: "City Events Wire",
NRA: "Non Regulatory Announcement",
ODP: "Offer Document Posted",
OFB: "Offer by (add offeror's name)",
OFD: "Statement re Possible Offer",
OFF: "Offer for (add offeree name)",
OLA: "Offer Lapsed",
ORE: "Offer Rejection",
OTT: "Offer Talks Terminated",
OUP: "Offer Update",
PAA: "AIM Prospective Admission",
PDI: "Publication of Prospectus",
PFU: "Portfolio Update",
PME: "Price Monitoring Extension",
PNM: "Prior Notice of Merger",
POS: "Transaction in Own Shares",
POT: "Statement re (POTAM)",
PRL: "Product Launch",
QRF: "1st Quarter Results",
QRT: "3rd Quarter Results",
RAG: "Result of AGM",
RAP: "Regulatory Application",
RC: "FRN Variable Rate Fix",
RDN: "Director Declaration",
RDS: "Director/PDMR Shareholding",
REA: "Regulatory Approval",
REG: "Result of EGM",
REN: "Restoration of Listing",
REP: "Restructure Proposals",
RES: "Research Update",
RET: "Rule 8.3- (add security name)",
ROI: "Result of Equity Issue",
ROM: "Result of Meeting",
RSP: "Response to(add further text)",
RTE: "Result of Tender Offer",
RTT: "Rule 2.10 Announcement",
SAL: "Re Alliance",
SEN: "London Stock Exchange Notice",
SOA: "Scheme of arrangement",
SPC: "Statement re. Press Comment",
SPM: "Stmnt re Share Price Movement",
SRS: "Statement re. Suspension",
SSD: "Short Selling Disclosure",
STA: "Stabilisation Notice",
STC: "Statement re. (COMP COMM)",
STR: "Statement re (add text)",
SUS: "Temporary Suspension",
SYR: "Syndicate Results",
TAB: "Disclosure Table",
TAV: "Total Assets Value",
TEN: "Tender Offer",
TRS: "Treasury Stock",
TSM: "Test Message",
TST: "Trading Statement",
TVR: "Total Voting Rights"
}